'use strict';

var assert    = require('assert');
var gutil     = require('gulp-util');
var pegjs     = require('./');

it('should generate a parser', function (cb) {
	var stream = pegjs();

	stream.on('data', function (file) {
		assert.equal(file.path, __dirname + '/fixture/fixture.js');
		assert.equal(file.relative, 'fixture/fixture.js');
		assert(/Generated by PEG\.js/.test(file.contents.toString()));
		cb();
	});

	stream.write(new gutil.File({
		base: __dirname,
		path: __dirname + '/fixture/fixture.pegjs',
		contents: new Buffer("start = ('a' / 'b')+")
	}));

  stream.end();
});
